//profile constants go here

export const PROFILE_GET_REQUEST = 'PROFILE_GET_REQUEST'
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS'
export const PROFILE_GET_FAIL = 'PROFILE_GET_FAIL'

export const MY_PROFILE_GET_REQUEST = 'MY_PROFILE_GET_REQUEST'
export const MY_PROFILE_GET_SUCCESS = 'MY_PROFILE_GET_SUCCESS'
export const MY_PROFILE_GET_FAIL = 'MY_PROFILE_GET_FAIL'